# 6-2. 프로젝트 (2) load_wine : 와인을 분류해 봅시다

(1) 필요한 모듈 import하기

In [1]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

(2) 데이터 준비

In [2]:
from sklearn.datasets import load_wine
wine = load_wine()

(3) 데이터 이해하기

In [3]:
wine.keys() #wine 데이터셋에 담긴 정보 종류 확인

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

◎ Feature Data 지정하기

In [4]:
# keys에서 확인한 정보 중 data를 따로 wine_data 변수에 저장
wine_data = wine.data

print(wine_data.shape) 
# shape는 배열의 형상정보를 출력
# 178개의 데이터가 각각 13개의 정보를 지니고 있음

(178, 13)


In [5]:
wine_data[0]
# 178개의 데이터 중 첫 번째 데이터 출력
# 총  13가지 화학 성분 수치 

array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
       3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
       1.065e+03])

In [6]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

◎ Label Data 지정하기

In [7]:
wine_label = wine.target
# keys에서 확인한 정보 중 target을 따로 wine_label 변수에 저장

print(wine_label.shape)
wine_label
# 178개의 숫자만 가지고 있음

(178,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

◎ Target Names 출력해 보기

In [8]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

◎ 데이터 Describe 해 보기

In [9]:
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

(4) train, test 데이터 분리

In [10]:
import pandas as pd

In [11]:
type(wine_data)

numpy.ndarray

In [12]:
wine_df = pd.DataFrame(data= wine_data, columns =wine.feature_names)
# 1797개 데이터가 각각 64개의 정보를 가지고 있던 wine_data를 
# wine.feature_names을 컬럼명으로 하는 DataFrame 자료형으로 변환해서 wine_df 변수에 저장
# (원래 wine_data는 배열(np.array) 자료형이었음!)
wine_df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [13]:
wine_df["label"] = wine.target
# wine_df에 label이라는 컬럼을 새로 추가
# 178개의 숫자로 이루어져 있었던 wine.target를 label 컬럼에 채워넣기
wine_df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  label  
0                            3.92   1065.0      0  
1                            3.40   1050.0      0  
2                            3.17   1185.0      0  
3                            3.45   1480.0      0  
4                            2.93    735.0      0  
..                            ...      ...    ...  
173                          1.74    740.0      2  
174                          1.56    750.0      2  
175                          1.56    835.0      2  
176                          1.62    840.0      2  
177                          1.60    560.0      2  

[178 rows x 14 columns]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(wine_data, 
                                                    wine_label, 
                                                    test_size=0.2, 
                                                    random_state=7,
                                                    stratify=wine_label)
# 나눠야 할 데이터(문제지, X): digits_data
# 데이터의 라벨(정답, y): wine_label
# wine_data와 wine_label를 각각 train:test = 8:2의 비율로 잘라서 
# X_train, X_test, y_train, y_test에 저장


print('X_train 개수: ', len(X_train),', X_test 개수: ', len(X_test))
# len은 배열의 길이를 출력

X_train 개수:  142 , X_test 개수:  36


In [15]:
X_train.shape, y_train.shape
# train의 형상정보 확인

((142, 13), (142,))

In [16]:
X_test.shape, y_test.shape
# test의 형상정보 확인

((36, 13), (36,))

In [17]:
y_train, y_test
# label이 잘 분리되었는지 확인

(array([2, 1, 1, 1, 2, 1, 2, 0, 0, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 0, 1, 1,
        2, 0, 1, 0, 0, 1, 1, 2, 1, 0, 0, 2, 1, 1, 0, 2, 1, 1, 0, 2, 0, 2,
        1, 0, 2, 2, 1, 2, 0, 1, 1, 0, 2, 0, 0, 2, 1, 2, 0, 2, 1, 0, 2, 2,
        0, 1, 2, 1, 1, 0, 2, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1,
        2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0, 2, 2, 2, 2, 1, 2, 0, 0,
        0, 1, 2, 1, 1, 0, 1, 1, 1, 2, 0, 0, 0, 2, 1, 0, 1, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 2, 1, 0, 1, 0, 2]),
 array([1, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 1, 1, 1, 2, 1, 0, 2, 2, 2, 0,
        1, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 0]))

(5) 다양한 모델로 학습시켜보기

◎ Decision Tree 사용해 보기

In [18]:
from sklearn.tree import DecisionTreeClassifier 
# sklearn.tree 패키지에서 의사결정트리 모델 import

decision_tree = DecisionTreeClassifier(random_state=32) 
# random_state : 재현가능하도록 난수의 초기값 32로 설정
print(decision_tree._estimator_type)

classifier


In [19]:
# 학습데이터 X_train, y_train로 의사결정나무 모델로 학습하기
decision_tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=32)

In [20]:
y_pred = decision_tree.predict(X_test)
y_pred

array([1, 0, 0, 0, 1, 0, 1, 2, 2, 2, 2, 0, 1, 2, 1, 2, 1, 0, 2, 2, 2, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 0])

In [21]:
# 진짜 정답
y_test

array([1, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 1, 1, 1, 2, 1, 0, 2, 2, 2, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 0])

In [22]:
# 실제 정답 y_test과 예측값 y_pred 비교하여 정확도 측정하기
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9444444444444444

In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        12
           1       0.93      0.93      0.93        14
           2       0.91      1.00      0.95        10

    accuracy                           0.94        36
   macro avg       0.95      0.95      0.95        36
weighted avg       0.95      0.94      0.94        36



◎ Random Forest 사용해 보기

In [24]:
from sklearn.ensemble import RandomForestClassifier #랜덤포레스트라는 분류기를 사용하기 위해 import

X_train, X_test, y_train, y_test = train_test_split(wine_data, # wine 데이터의 data 컬럼
                                                    wine_label, # wine 데이터의 target 컬럼
                                                    test_size=0.2, # test_size : train data와 test data를 몇대몇으로 나눌지 정하는 옵션
                                                    random_state=7,
                                                    stratify=wine_label) # random_state : 랜덤 패턴의 값을 지정

random_forest = RandomForestClassifier(random_state=32) # RandomForest분류기 객체를 생성
random_forest.fit(X_train, y_train) # 훈련
y_pred = random_forest.predict(X_test) # 예측

print(classification_report(y_test, y_pred)) # 결과 지표를 확인

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.93      0.96        14
           2       0.91      1.00      0.95        10

    accuracy                           0.97        36
   macro avg       0.97      0.98      0.97        36
weighted avg       0.97      0.97      0.97        36



◎ SVM 사용해 보기

In [25]:
#Support Vector Machine (SVM)
from sklearn import svm #Support Vector Machine을 사용하기 위해 import
svm_model = svm.SVC() # 모델 객체를 만든다.

print(svm_model._estimator_type) # 이 모델이 어떤 타입인지 확인한다.

classifier


In [26]:
svm_model.fit(X_train,y_train)
y_pred = svm_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.60      0.86      0.71        14
           2       0.29      0.20      0.24        10

    accuracy                           0.64        36
   macro avg       0.63      0.60      0.60        36
weighted avg       0.65      0.64      0.63        36



◎ SGD Classifier 사용해 보기

In [27]:
#Stochastic Gradient Descent Classifier (SGDClassifier)
from sklearn.linear_model import SGDClassifier #선형분류기인 SGDClassifier를 사용하기 위한 import
sgd_model = SGDClassifier() # 모델 객체 생성

print(sgd_model._estimator_type) # 이 모델의 타입을 확인

classifier


In [28]:
sgd_model.fit(X_train,y_train)
y_pred = sgd_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.92      0.65        12
           1       0.79      0.79      0.79        14
           2       0.00      0.00      0.00        10

    accuracy                           0.61        36
   macro avg       0.43      0.57      0.48        36
weighted avg       0.47      0.61      0.52        36



/opt/conda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


◎ Logistic Regression 사용해 보기

In [29]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression # 선형분류기인 LogisticRegression를 사용하기 위한 import
logistic_model = LogisticRegression() # 모델 객체 생성

print(logistic_model._estimator_type) # 이 모델의 타입을 확인

classifier


In [30]:
logistic_model.fit(X_train,y_train)
y_pred = logistic_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.81      0.93      0.87        14
           2       0.90      0.90      0.90        10

    accuracy                           0.89        36
   macro avg       0.90      0.89      0.89        36
weighted avg       0.90      0.89      0.89        36



/opt/conda/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


다중 클래스 분류에서는 특정 클래스의 개별 성능보다는 모델의 전반적인 균형과 성능을 평가하는 것이 중요하다.
따라서 Accuracy뿐만 아니라, F1-score 같은 종합적인 지표를 추가적으로 고려하는 것이 바람직하다.
Q. 오류의 원인은 label이 불균형하게 분포되어있는 데이터라서 발생하는 것인가?